### ISSUE TITLE
Insufficient Exception Information When Status Code 403 / Forbidden

### ISSUE THREAD

**Issue by arawin1979** [box/box-windows-sdk-v2#148]
Steps to reproduce the issue
1. Create an Application for Box Platform
2. Configure the Public Key to authenticate with JWT
3. Create App User pragmatically 
4. Either set default Storage Quota as 0 for newly created users / Change the Storage Quota as 0 for the create user.
5. Uploading a file will result in a below mentioned exception.

Though the actual response has the detail but it is not properly bubbled to the caller.  

**Exception Detail**
Box.V2.Exceptions.BoxException was unhandled by user code
  HResult=-2146233088
  Message=Forbidden
  Source=Microsoft.Threading.Tasks
  StackTrace:
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
       at Box.V2.Managers.BoxFilesManager.<UploadAsync>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at BoxJWT.Program.<DoSomething>d__1.MoveNext() in C:\Users\u1cc62\01.Main\RnD\BoxRnD\BoxJWT\Program.cs:line 155
  InnerException:

**Comment by cburnette** [comment]
Added with 2.10.0
