### ISSUE TITLE
Cannot access a closed Stream - Upload, Upload New Version - Rate Limit Retry

### ISSUE THREAD

**Issue by john-potter** [box/box-windows-sdk-v2#266]
It appears a stream is being disposed of during upload attempts and subsequent rate limit retries result in an error "Cannot access a closed Stream".

v2.13.0 SDK

Message: Error while copying content to a stream.
Inner Exception: System.ObjectDisposedException: Cannot access a closed Stream.
at System.IO.__Error.StreamIsClosed()
at System.IO.MemoryStream.get_Position()
at System.Net.Http.StreamToStreamCopy.StartAsync()
at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
at Box.V2.Managers.BoxFilesManager.<UploadAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by coolboy** [comment]
@john-potter 

How large is your file?
1. Try use timeout for UploadAsync()
2. Try use UploadUsingSessionAsync() on SDK version 2.15

Closing this issue now, but feel free to reopen it
