### ISSUE TITLE
Require cryptography library not present on OSX Core

### ISSUE THREAD

**Issue by cburnette** [box/box-windows-sdk-v2#344]
Exception is thrown when using JWT stuff on a Mac and the private key is the new format being generated by Box from the app console.  CspParameters constructor fails because libraries are missing from OSX version of .net core.

here's a relevant discussion:
https://github.com/dotnet/corefx/issues/17163

**Comment by cburnette** [comment]
So after a little more poking around it seems like this line:

https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2.JWTAuth/RSAUtilities.cs#L28

is resolving as true even though I'm running my code on OSX.  Not sure why that would be, but the error indicates that it clearly is going down the path of trying to instantiate CspParameters.

Connection id "0HL5DU92LTMD1": An unhandled exception was thrown by the application.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Security.Cryptography.CspParameters..ctor()
   at Box.V2.JWTAuth.DotNetUtilities.CreateRSAProvider(RSAParameters rp)
   at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig)
   at BoxCDN.BoxPlatform.Service.BoxPlatformService..ctor(IOptions`1 boxPlatformSettings, IBoxPlatformCache boxPlatformCache) in /Users/cburnette/code/dotnet/BoxCDN/BoxPlatform/Service/BoxPlatformService.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

**Comment by coolboy** [comment]
Fixed this by removing the if Window, and using RSA.Create() as always

`yhu@mbp-003130 publish $ ls -l Box.V2.*
-rwxr-xr-x@ 1 yhu  AD\Domain Users  343040 Jul 11 11:48 Box.V2.Core.dll
-rwxr-xr-x@ 1 yhu  AD\Domain Users   78844 Jul 11 11:48 Box.V2.Core.pdb
-rwxr-xr-x@ 1 yhu  AD\Domain Users  155976 Jun 15  2016 Box.V2.Samples.Core.AppUser.Create
-rwxr-xr-x@ 1 yhu  AD\Domain Users  139401 Jul 11 11:49 Box.V2.Samples.Core.AppUser.Create.deps.json
-rwxr-xr-x@ 1 yhu  AD\Domain Users    9216 Jul 11 11:49 Box.V2.Samples.Core.AppUser.Create.dll
-rwxr-xr-x@ 1 yhu  AD\Domain Users    1260 Jul 11 11:49 Box.V2.Samples.Core.AppUser.Create.pdb
-rwxr-xr-x@ 1 yhu  AD\Domain Users      28 Jul 11 11:49 Box.V2.Samples.Core.AppUser.Create.runtimeconfig.json
yhu@mbp-003130 publish $ ./Box.V2.Samples.Core.AppUser.Create
Json file path: 
app_config_coolcute_live.json
New app user created with Id = 2047091060
New folder created with Id = 31923217824
New file uploaded with Id = 195875184628 in 1949 ms
yhu@mbp-003130 publish $ `
