### ISSUE TITLE
JWTAuth key issue

### ISSUE THREAD

**Issue by GarMGarM** [box/box-windows-sdk-v2#396]
I am getting errors running JWTAuth. Errors vary by key creation method:-

Using Cygwin64 created keys (as per documentation instructions):

Error message: pad block corrupted

Error stack trace:

	at Org.BouncyCastle.Crypto.Paddings.Pkcs7Padding.PadCount(Byte[] input)
	at Org.BouncyCastle.Crypto.Paddings.PaddedBufferedBlockCipher.DoFinal(Byte[] output, Int32 outOff)
	at Org.BouncyCastle.Crypto.BufferedBlockCipher.DoFinal(Byte[] input, Int32 inOff, Int32 inLen)
	at Org.BouncyCastle.Crypto.BufferedCipherBase.DoFinal(Byte[] input)
	at Org.BouncyCastle.OpenSsl.PemUtilities.Crypt(Boolean encrypt, Byte[] bytes, Char[] password, String dekAlgName, Byte[] iv)
	at Org.BouncyCastle.OpenSsl.PemReader.ReadPrivateKey(PemObject pemObject)
	at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()
	at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig)
   
   
Using Box provided Key pair:
 
Error message: -----END ENCRYPTED PRIVATE KEY not found

Error stack trace:

	at Org.BouncyCastle.Utilities.IO.Pem.PemReader.LoadObject(String type)
	at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()
	at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig) in C:\...\Box.V2\JWTAuth\BoxJWTAuth.cs:line 60
	at Box.V2.Samples.JWTAuth.Program.<MainAsync>d__6.MoveNext() in C:\...\Box.V2.Samples.JWTAuth\Program.cs:line 37
	--- End of inner exception stack trace ---
	at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	at System.Threading.Tasks.Task.Wait()
	
Both are reading from .pem file.

**Comment by ohadschn** [comment]
I got the same with the Box-provided Key pair, and this resolved it:
https://stackoverflow.com/a/33318003/67824

**Comment by GarMGarM** [comment]
@ohadschn  Thanks - that seems to have resolved the " -----END ENCRYPTED PRIVATE KEY not found " error.
Both key types are now producing the "pad block corrupted" error - so at least consistent!

**Comment by coolboy** [comment]
Hi @GarMGarM 

Will not Box provided Key pair be enough for you? Why do you still need to fix the `pad block corrupted` from Cygwin64 created keys?

**Comment by GarMGarM** [comment]
So, I have a working solution of sorts - using the key pair provided by BOX, modified as per suggestion above by @ohadschn

// reading the private key from app.config file - does **not** work:
static readonly string JWT_PRIVATE_KEY = ConfigurationManager.AppSettings["boxPrivateKey"];

// reading the private key from pem file - does **not** work:
var privateKey = File.ReadAllText("private_key.pem");

// replacing above code (var privateKey = ...) with this and it works!
string privateKey = "-----BEGIN ENCRYPTED PRIVATE KEY-----\r\n#######\r\n-----END ENCRYPTED PRIVATE KEY-----\n";

**Comment by ohadschn** [comment]
@GarMGarM there should be no difference between the three methods you listed. If you got it to work using the third (hard-coded variable), you can get it to work using the first two (`app.config` and `private_key.pem`). 

I recommend you print out the strings you got in all methods and put them in something like KDiff3, you'll see the difference (probably related to newlines / whitespace).

**Comment by GarMGarM** [comment]
@ohadschn I agree, there should be no difference. In debug mode all appear identical by type and value. I'll come back to this when I have completed my current work requirement and see if I can identify the underlying issue.

**Comment by ohadschn** [comment]
@GarMGarM looks can be deceiving - you have to use a proper differ and include all special characters (like tabs, spaces, and EOL). Something is different...

**Comment by danblair** [comment]
Just to offer a possible solution for the AppSettings.  If you copy a string with '\n' characters into a string field it actually encodes it as '\\''n' so you see a literal "\n" if you open the app.config file.  You need to replace those values with a newline in the app.config file.
