### ISSUE TITLE
Chunked Upload stream closing error

### ISSUE THREAD

**Issue by carycheng** [box/box-windows-sdk-v2#463]
Description of the Issue
Using the Box V2 SDK for Chunked Uploads and I'm getting the following error in "UploadPartAsync" method: System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a closed Stream.
I'll include my log statements and stack trace below. I'm attempting to send a 50MB file (also happens on all files I try) using Chunked Uploading. It's sending all 7 parts and getting a 200 response back for all parts. but then after the last part, the session commit doesn't happen and I get the above closed Stream error.
Wondering if you've seen this before? It seems like it's trying to call UploadPartAsync an 8th time after the stream is already closed. I had it working a couple weeks ago with the same files (>20MB), but now can't send any. I haven't changed any of the code between it working and not working.

Versions Used
Java SDK: Box.V2 3.4.2
Java: Version 8, Update 161

Steps to Reproduce
Steps to reproduce are to hit Archive project on our web application.
Flow of SDK methods being called are: UploadUsingSessionAsync, which first calls CreateUploadSessionAsync (successfully creates Upload session), then UploadSessionAsync > UploadPartsInSessionAsync > UploadPartAsync (failing here after last part gets sent). It should then call CommitSessionAsync but it's not getting there.

Error Message, Including Log Statements and Stack Trace
22-Mar-18	10:40:35.687	[Viki.sProcessingQueue.18068.50]	{History}	Job "New Archive test" has been queued for archiving
22-Mar-18	10:40:38.055	[Viki.sProcessingQueue.18068.8]	{Archiving}	Archiving file SCTZ-0524.pdf	, attempt 1	of 3
22-Mar-18	10:40:38.056	[Viki.sProcessingQueue.18068.8]	{Archiving}	Creating Upload session with uri https://upload.box.com/api/2.0/files/upload_sessions
22-Mar-18	10:40:39.059	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 0	- 8388607	/	50773750
22-Mar-18	10:40:39.106	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 8388608	- 16777215	/	50773750
22-Mar-18	10:40:39.150	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 16777216	- 25165823	/	50773750
22-Mar-18	10:40:39.190	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 25165824	- 33554431	/	50773750
22-Mar-18	10:40:39.229	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 33554432 -	41943039	/	50773750
22-Mar-18	10:40:49.639	[Viki.sProcessingQueue.18068.23]	{Archiving}	Uploading File part 41943040 -	50331647	/	50773750
22-Mar-18	10:40:50.408	[Viki.sProcessingQueue.18068.35]	{Archiving}	Uploading File part 50331648 -	50773749	/	50773750
22-Mar-18	10:41:11.647	[Viki.sProcessingQueue.18068.8]	{Archiving}	Caught exception in UploadFile, destinationPath \Bass\Jobs\New_Archive_test-1095\FileTransfers\1267	, path c:\DataStores\Root\Bass\Jobs\New_Archive_test-1095\FileTransfers\1267\SCTZ-0524.pdf	, exception System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a closed Stream.
at System.IO.__Error.StreamIsClosed()
at System.IO.MemoryStream.get_Length()
at Viki.bBase.bnJobArchiver.BoxFilesManager.d__3.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 896
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadPart>d__9.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1120 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at Viki.bBase.bnJobArchiver.BoxFilesManager.d__8.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1103
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadSessionAsync>d__7.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1011 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at Viki.bBase.bnJobArchiver.BoxFilesManager.d__6.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 971
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at Viki.bBase.bnJobArchiver.bcBoxDotComArchiver.UploadFile(String destinationPath, String path) in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 414
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a closed Stream.
at System.IO.__Error.StreamIsClosed()
at System.IO.MemoryStream.get_Length()
at Viki.bBase.bnJobArchiver.BoxFilesManager.d__3.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 896
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadPart>d__9.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1120 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at Viki.bBase.bnJobArchiver.BoxFilesManager.d__8.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1103
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadSessionAsync>d__7.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1011 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at Viki.bBase.bnJobArchiver.BoxFilesManager.d__6.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 971<---

**Comment by carycheng** [comment]
Hey @jessicaviki, 

1. We tested the `UploadUsingSessionAsync()` with a 50mb file and it seems to be working okay on our end. 
2. The way that the SDK determines the number of parts to upload is from the Length property on the Stream. Could you check if the Stream.Length property is accurate and what you expect using the code below?

```c#
var statedLength = stream.Length;
var memoryStream = new MemoryStream();
stream.CopyTo(memoryStream);
var actualLength = memoryStream.ToArray().Length;
```

**Comment by jessicaviki** [comment]
Hey @carycheng 
I put that snippet in. For my test file, both the statedLength and the actualLength are the same (50773750). I'm getting partsize = 8388608, and number of parts = 7 (which is the number of parts that are getting sent before I get the Stream closed error).

**Comment by carycheng** [comment]
Hey @jessicaviki, 

Curious what version of .Net Framework/Core/Mono you are currently running on? Also if you could let us know what type of stream you are using(e.g FileStream)? 

Thanks!

**Comment by jessicaviki** [comment]
@carycheng 
Stream stream = new FileStream( path, FileMode.Open, FileAccess.Read )
and I'm running on Net Framework 4.7.02556

**Comment by carycheng** [comment]
Hey @jessicaviki, 

We just tested the `UploadingUsingSessionAsync()` with a file size of 50773750 and we were able to commit and upload successfully. Below is the snippet we ran. Can you please try the below and see if this works or if there are any differences between how you are currently implementing the chunked upload? Thank you 

```C#
FileStream fileStream = new FileStream(pathToFile, FileMode.Open, FileAccess.Read);
var statedSize = fileStream.Length; // returns 50773750
var progress = new Progress<BoxProgress>(val =>
{
    Debug.WriteLine("{0}%", val.progress);
});
var file = await client.FilesManager.UploadUsingSessionAsync(fileStream, "test.txt", "0",
                null, progress);
```

**Comment by jessicaviki** [comment]
Hey @carycheng 
I did a bit more debugging and tried the above snippet -- turns out I had put in a debug statement that was trying to read the stream.Length after the stream was closed (hence the Stream disposed error). *Facepalm*
thank you for your help, it seems to be working now.

**Comment by carycheng** [comment]
Glad we were able to resolve this! Let us know if anything else comes up, thanks!
