### ISSUE TITLE
MoveUserfolderasync method errors out

### ISSUE THREAD

**Issue by whiggs** [box/box-windows-sdk-v2#481]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
The MoveUserfolderasync method of the box.v2.managers.Boxusersmanagers object is faulting due to what appears to be a timeout error when running the box windows sdk in powershell.  I have the below code:
`$move = $adminclient.Usersmanager.moveuserfolderasync($user.ID, "<userid of destination>, "0")
$move.Wait
And there are times, when I run this code, that it works perfectly, and there are times where the "Wait" method returns an error because the task associated with the $move variable faulted because it times out.  I have attached a text file which contains the returned information that is stored in the $move variable when these faults occur.  However, this should not be happening, as the process is still being executed when these faults occur.  I know this is the case because if I wait for a minute or two and try re-running the command against the user again, it will complete successfully, and generate ANOTHER folder in the destination account with the "user's files", but that folder will be empty.  Also, when these faults occur, if I login to the destination account and try to move the folder containing the user's files before the process has actually finished executing, I get this popup:
![image](https://user-images.githubusercontent.com/11139575/39362384-403db4f0-49f4-11e8-8df3-b0bed0b17f3b.png)

Why is this happening?  Why am I sometimes getting this error and sometimes not.  This is very disrupting to my attempts to automate certain processes, and is creating a lot of extra work for me, so a fix would be VERY appreciated.
[box error.txt](https://github.com/box/box-windows-sdk-v2/files/1955043/box.error.txt)

### Versions Used
.NET SDK: // v3.7.0
.NET Framework/Core: // NA.  This is in a powershell session using the box.v2 nuget packages

### Steps to Reproduce
Already explained above

### Error Message, Including Stack Trace
Result                 : 
Id                     : 177877
Exception              : System.AggregateException: One or more errors occurred. ---> Box.V2.Exceptions.BoxConflictException`1[Box.V2.Models.BoxFolder]: 
                         {"type":"error","status":409,"code":"conflict","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"User is 
                         locked","request_id":"rlc7hqfqquszcuoo"}
                            at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)
                            at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__11`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Box.V2.Managers.BoxUsersManager.<MoveUserFolderAsync>d__13.MoveNext()
                            --- End of inner exception stack trace ---
                         ---> (Inner Exception #0) Box.V2.Exceptions.BoxConflictException`1[Box.V2.Models.BoxFolder]: 
                         {"type":"error","status":409,"code":"conflict","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"User is 
                         locked","request_id":"rlc7hqfqquszcuoo"}
                            at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)
                            at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__11`1.MoveNext()
                         --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Box.V2.Managers.BoxUsersManager.<MoveUserFolderAsync>d__13.MoveNext()<---
                         
Status                 : Faulted
IsCanceled             : False
IsCompleted            : True
CreationOptions        : None
AsyncState             : 
IsFaulted              : True
AsyncWaitHandle        : System.Threading.ManualResetEvent
CompletedSynchronously : False

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by whiggs** [comment]
Result                 : 
Id                     : 184357
Exception              : System.AggregateException: One or more errors occurred. 
                         ---> Box.V2.Exceptions.BoxException: <html><body><h1>504 
                         Gateway Time-out</h1>
                         The server didn't respond in time.
                         </body></html>
                         
                            at Box.V2.Extensions.BoxResponseExtensions.ParseResults[
                         T](IBoxResponse`1 response, IBoxConverter converter)
                            at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d
                         __11`1.MoveNext()
                         --- End of stack trace from previous location where 
                         exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInf
                         o.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
                         SuccessAndDebuggerNotification(Task task)
                            at Box.V2.Managers.BoxUsersManager.<MoveUserFolderAsync>
                         d__13.MoveNext()
                            --- End of inner exception stack trace ---
                         ---> (Inner Exception #0) Box.V2.Exceptions.BoxException: 
                         <html><body><h1>504 Gateway Time-out</h1>
                         The server didn't respond in time.
                         </body></html>
                         
                            at Box.V2.Extensions.BoxResponseExtensions.ParseResults[
                         T](IBoxResponse`1 response, IBoxConverter converter)
                            at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d
                         __11`1.MoveNext()
                         --- End of stack trace from previous location where 
                         exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInf
                         o.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
                         SuccessAndDebuggerNotification(Task task)
                            at Box.V2.Managers.BoxUsersManager.<MoveUserFolderAsync>
                         d__13.MoveNext()<---
                         
Status                 : Faulted
IsCanceled             : False
IsCompleted            : True
CreationOptions        : None
AsyncState             : 
IsFaulted              : True
AsyncWaitHandle        : System.Threading.ManualResetEvent
CompletedSynchronously : False

**Comment by whiggs** [comment]
Ah.  In that case, as long as you are aware of the issues existence and it is being actively worked on, then I guess this issue can be closed.  Thank you for the info.
