### ISSUE TITLE
Can't query root folders or specific folder (specified id is passed as "d_1703015400"?)

### ISSUE THREAD

**Issue by sebasijan** [box/box-windows-sdk-v2#487]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

Trying to get some folder items from a folder that was shared wit me. It works when using the API explorer, but when using the SDK I get an error

 > {"type":"error","status":404,"code":"not_found","context_info":{"errors":[{"reason":"invalid_parameter","name":"folder","message":"Invalid value 'd_1703015400'. 'folder' with value 'd_1703015400' not found"}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Not Found","request_id":"fugh0sfre5ce6wmi"}

The folder ID is `1703015400`

My code:

    public async Task GetAllFolderIds()
    {
        var boxItems = await client.FoldersManager.GetFolderItemsAsync("1703015400", 1000);
    }

Also note when specifying an id of `0` I just get an empty box collection, where I could expect to see the items that were shared with me. 

I am using JWT authentication with all permission scopes.

### Versions Used
.NET SDK:<PackageReference Include="Box.V2.Core" Version="3.3.0"/>
.NET Framework/Core: 2.0

### Steps to Reproduce

Install the SDK, gain access the the folder, run the code above calling the specified id.

### Error Message, Including Stack Trace

 An unhandled exception has occurred while executing the request

	Box.V2.Exceptions.BoxException: {"type":"error","status":404,"code":"not_found","context_info":{"errors":[{"reason":"invalid_parameter","name":"folder","message":"Invalid value 'd_1703015400'. 'folder' with value 'd_1703015400' not found"}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Not Found","request_id":"sp1j81fre5nfimh9"}

	   at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)

	   at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__9`1.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Box.V2.Managers.BoxFoldersManager.<GetFolderItemsAsync>d__2.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

	   at DSSTools.Managers.BoxManager.<GetAllFolderIds>d__26.MoveNext() in C:\Users\sebastian.kotze\source\repos\TFS\DSSTools\Managers\BoxManager.cs:line 230

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

	   at DSSTools.Controllers.HomeController.<Test>d__3.MoveNext() in C:\Users\sebastian.kotze\source\repos\TFS\DSSTools\Controllers\HomeController.cs:line 35

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

	Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request

	Box.V2.Exceptions.BoxException: {"type":"error","status":404,"code":"not_found","context_info":{"errors":[{"reason":"invalid_parameter","name":"folder","message":"Invalid value 'd_1703015400'. 'folder' with value 'd_1703015400' not found"}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Not Found","request_id":"sp1j81fre5nfimh9"}

	   at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)

	   at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__9`1.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Box.V2.Managers.BoxFoldersManager.<GetFolderItemsAsync>d__2.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

	   at DSSTools.Managers.BoxManager.<GetAllFolderIds>d__26.MoveNext() in C:\Users\sebastian.kotze\source\repos\TFS\DSSTools\Managers\BoxManager.cs:line 230

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

	   at DSSTools.Controllers.HomeController.<Test>d__3.MoveNext() in C:\Users\sebastian.kotze\source\repos\TFS\DSSTools\Controllers\HomeController.cs:line 35

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()

	--- End of stack trace from previous location where exception was thrown ---

	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

	   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
		 

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by sebasijan** [comment]
Note that I am using JWT auth, and my application is authenticating using app id, app secret and a public/private key pair.

if I generate a (60 minute) developer token, I can call the API normally using that just fine in (for example) PowerShell. 

What does this mean? Am I stupid?

**Comment by carycheng** [comment]
Hey @sebasijan, 

Apologies if the set up is a bit confusing! When you set up auth, if you are using JWT auth, something similar to [this](https://github.com/box/box-windows-sdk-v2/blob/master/docs/authentication.md#server-auth-with-jwt), you are actually authenticating with a [service account ](https://developer.box.com/docs/service-account). A service account by default only has access to items that you've stored at the application level and not the user level - that could be why you are receiving that 404 since it does not actually have access to those folder items. 

You can try the following to return your items:

1. Make the GetFolderItemsAsync() call again as a specific Box user with this snippet here
```#C
var userId = "12345";
var client = new BoxClient(config, session, asUser: userId);
```
2. Once you have the client, use the same snippet you used earlier but call the GetfolderItemsAsync() with the client now, similar to how you were doing it earlier.

You just have to make sure that the user you are calling on behalf of is a collaborator on that folder.

Let us know if that helps thank you!
