### ISSUE TITLE
.NET SDK Metadata Template API Issue

### ISSUE THREAD

**Issue by Umkqq** [box/box-windows-sdk-v2#494]
The issue was submitted here first: 
https://community.box.com/
ticket id:1702655

### Description of the Issue
 Metadata_UpdateTemplate_LiveSession() Integration test fails with number of different "Update" errors.

### Versions Used
.NET SDK: 3.9.2 - master - commit hash - 5800ee9aa621493d6d23d8628b2bf5b20057309a. 
.NET Framework/Core: 4.5

### Steps to Reproduce
Run integration test Metadata_UpdateTemplate_LiveSession() number of times (1 to 5).

Repository class: 
https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2.Test.Integration/BoxMetadataManagerTestIntegration.cs.

Test name - Metadata_UpdateTemplate_LiveSession(). 
In some cases UpdateMetadataTemplate method returns error on different steps of the test.

Last time issue was reproduced, it returned BoxException with the folowing message: 
Box.V2.Exceptions.BoxException: The API returned an error [BadRequest | ...] bad_request - 
Could not find field: attr5

Failed code: 
update = new BoxMetadataTemplateUpdate() { Op = MetadataTemplateUpdateOp.removeField, FieldKey = "attr5" }; 
updates = new List<BoxMetadataTemplateUpdate>() { update }; 
updatedTemplate = await _client.MetadataManager.UpdateMetadataTemplate(updates, "enterprise", templateKey);

The first step of the test is to create attr5. 
This issue is not reproduced consistently. 

### Error Message, Including Stack Trace
Test method Box.V2.Test.Integration.BoxMetadataManagerTestIntegration.Metadata_UpdateTemplate_LiveSession threw exception: 
Box.V2.Exceptions.BoxException: The API returned an error [BadRequest | ...] bad_request - Could not find field: attr5
    at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter) in ...\Box.V2\Extensions\BoxResponseExtensions.cs:line 81
   at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__11`1.MoveNext() in ...\Box.V2\Managers\BoxResourceManager.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Box.V2.Managers.BoxMetadataManager.<UpdateMetadataTemplate>d__12.MoveNext() in ...\Box.V2\Managers\BoxMetadataManager.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Box.V2.Test.Integration.BoxMetadataManagerTestIntegration.<Metadata_UpdateTemplate_LiveSession>d__13.MoveNext() in ...\Box.V2.Test.Integration\BoxMetadataManagerTestIntegration.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @Umkqq, 

Thank for writing in, just to clarify, does the `Metadata_UpdateTemplate_LiveSession()` giving an error or is the general `MetadataManager.UpdateMetadataTemplate()` call that is called from that test giving an error?

**Comment by Umkqq** [comment]
Hey,
Error occures on this line:
updatedTemplate = await _client.MetadataManager.UpdateMetadataTemplate(updates, "enterprise", templateKey);
So error is given by UpdateMetadataTemplate().

**Comment by carycheng** [comment]
@Umkqq, 

We will look into this, apologies for any inconvenience!

**Comment by mattwiller** [comment]
@Umkqq Just to be clear, are you encountering an error in your own use of `client.MetadataManager.UpdateMetadataTemplate`, or is it just the integration test that's failing?

**Comment by Umkqq** [comment]
@mattwiller Integration test is failing. I haven't tried to reproduce it another way.
