### ISSUE TITLE
Conflicts BouncyCastle

### ISSUE THREAD

**Issue by SmartDuck72** [box/box-windows-sdk-v2#609]
**Problem**
In my library project when I create a instance of BoxJWTAuth I keep getting the error:

System.IO.FileLoadException
  HResult=0x80131040
  Message=Kan bestand of assembly BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=0e99375e54769942 of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. 

**Checked so far**
I have set log verbosity to detailed but see no extra information in my build log.
I have checked that the versions of the nuget packages are the same as that of the 3.20  version of the SDK.  Removed all objects and binaries, cleaned the solution en rebuild all.
A conflict between the reference loaded by nuget and the version internal used bij the BoxSDK?

**Software versions**
.NET framework: 4.5.1
BouncyCastle: 1.8.1
Box.V2: 3.20.0
Microsoft.IdentityModel.Logging: 1.1.4
Microsoft.IdentityModel.Tokens: 5.1.4
Newtonsoft.Json: 10.0.3
System.IdentityModel.Tokens.Jwt: 5.1.4

**Complete Error Message**
System.IO.FileLoadException
  HResult=0x80131040
  Message=Kan bestand of assembly BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=0e99375e54769942 of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. (Uitzondering van HRESULT: 0x80131040)
  Source=Box.V2
  StackTrace:
   at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig, IBoxService boxService)
   at DMG.BoxLibrary.BoxAuthentication..ctor(String authenticationFile, BoxAuthMode boxAuthMode, String token) in C:\WS_EGL95\DMG_Lasernet_Modules\BoxModules\BoxLibrary\BoxAuthentication.cs:line 56
   at BoxTest.BoxTestForm.authenticate() in C:\WS_EGL95\DMG_Lasernet_Modules\BoxModules\BoxTest\BoxTestForm.cs:line 276
   at BoxTest.BoxTestForm.searchFiles() in C:\WS_EGL95\DMG_Lasernet_Modules\BoxModules\BoxTest\BoxTestForm.cs:line 315
   at BoxTest.BoxTestForm.BtnSearch_Click(Object sender, EventArgs e) in C:\WS_EGL95\DMG_Lasernet_Modules\BoxModules\BoxTest\BoxTestForm.cs:line 307
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at BoxTest.Program.Main() in C:\WS_EGL95\DMG_Lasernet_Modules\BoxModules\BoxTest\Program.cs:line 19

Inner Exception 1:
FileLoadException: Kan bestand of assembly BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942 of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. (Uitzondering van HRESULT: 0x80131040)

**Comment by nidoran** [comment]
Hi @SmartDuck72 , just wondering, do you have BouncyCastle.Crypto, Version=1.8.5.0 specified in your application or any other libraries you are using in your application?

**Comment by SmartDuck72** [comment]
I have searched for the 1.8.5 version in the 4 projects of my solution, couldn't find it so far.

![package](https://user-images.githubusercontent.com/56966523/67551733-db72a200-f709-11e9-8147-e45f893bca49.PNG)

![Bouncycatle](https://user-images.githubusercontent.com/56966523/67551740-df9ebf80-f709-11e9-9e5a-5aa12a32012a.PNG)

**Comment by SmartDuck72** [comment]
Problem found!

I have updated the packages to the latest versions before for testing. After testing I reinstalled the packages to the version recommended for the sdk.
Visual Studio didn't downgrade the app.config and that is the cause of the conflict:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Tokens" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.0.0" newVersion="5.6.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Logging" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.0.0" newVersion="5.6.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.0.0" newVersion="5.6.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="BouncyCastle.Crypto" publicKeyToken="0e99375e54769942" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.8.5.0" newVersion="1.8.5.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
