### ISSUE TITLE
Regression Bug: JsonSerializationException for GetCurrentUserInformationAsync

### ISSUE THREAD

**Issue by DaleyKD** [box/box-windows-sdk-v2#669]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Just upgrade from Box.V2.Core 3.**22**.0 to 3.**23**.0. A regression issue has bubbled up.

I can no longer call `var user = await boxClient.UsersManager.GetCurrentUserInformationAsync();` without the a Newtonsoft deserialization issue.  See Stack Trace below for further details.

### Steps to Reproduce
```csharp
internal BoxClient GetBoxUserClient(string userID)
{
    var boxConfig = new BoxConfig(this.ClientID, this.ClientSecret, this.EnterpriseID, this.PrivateKey, this.PrivateKeyPassphrase, this.PublicKeyID);
    var boxJwt = new BoxJWTAuth(boxConfig);
    var userToken = boxJwt.UserToken(userID);
    return boxJwt.UserClient(userToken, userID);
}
```

```csharp
var boxClient = GetBoxUserClient("validuser@mydomain.com");
var user = await boxClient.UsersManager.GetCurrentUserInformationAsync();
```

Use the above code in version 3.22.0: Works.
Use the above code in version 3.23.0: Exception thrown.

### Expected Behavior
Not have an exception thrown.

### Error Message, Including Stack Trace
```
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Box.V2.Models.BoxNotificationEmail' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'notification_email', line 1, position 451.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Box.V2.Converter.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Box.V2.Converter.BoxJsonConverter.Parse[T](String content)
   at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)
   at Box.V2.Managers.BoxResourceManager.ToResponseAsync[T](IBoxRequest request, Boolean queueRequest)
   at Box.V2.Managers.BoxUsersManager.GetCurrentUserInformationAsync(IEnumerable`1 fields)
```

### Versions Used
.Net SDK: .NET Core 3.1.4
Windows: Windows 10 (1909) 64-bit

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@DaleyKD Looking into this issue now.

**Comment by deleepgeorge** [comment]
BoxNotificationEmail property of BoxUser  (BoxUser.cs) should be an array. 

If you look at the UI (account settings), user is allowed to add more than one alternate notification email. 

-- This is where it is failing
BoxItemConverter.cs > ReadJson(..)
serializer.Populate(jObject.CreateReader(), target);

**Comment by sujaygarlanka** [comment]
@deleepgeorge @DaleyKD We are going to push out a patch next week for this.

**Comment by DaleyKD** [comment]
@sujaygarlanka It's been over two weeks; any updates?

**Comment by sujaygarlanka** [comment]
Hey @DaleyKD, Sorry about the delay. We have been speaking with our backend team in charge of the API endpoint about fixing the endpoint and thereby fixing the SDK. They are not planning on fixing this in the API soon, so we will implement a fix and role it out this sprint (i.e. June 26th). Sorry for any difficulty this has caused.

**Comment by DaleyKD** [comment]
Truly no worries for me. We aren't rolling out our Box implementation yet.  I just wanted to make sure this wasn't lost.

Totally understand, and really appreciate the reply.  Keep up the good work.

**Comment by Erapchu** [comment]
I have the same bug. Something wrong with this field.
![image](https://user-images.githubusercontent.com/37536541/85251154-c4e03e80-b482-11ea-9a97-eb53b90f5f4c.png)

But thanks a lot to API for .NET => you can retrieve fields what you want.
`public Task<BoxUser> GetCurrentUserInformationAsync(IEnumerable<string> fields = null);`
Any fields that supported. Like in this case except problematic field.

**Comment by sujaygarlanka** [comment]
Fix merged. Going to do a release next week.

**Comment by guynamedneil** [comment]
@sujaygarlanka Hey, is this release still coming very soon? The deserialization issue is also causing GetEnterpriseUsersAsync and CreateEnterpriseUserAsync to throw. Thank you!

**Comment by sujaygarlanka** [comment]
@guynamedneil Sorry for the delay. New release has been cut with the fix and some other added features.
