### ISSUE TITLE
Unable to retrieve folder contents sorted by date

### ISSUE THREAD

**Issue by daren09** [box/box-windows-sdk-v2#715]
Note that retrieving contents sorted by name works using;
 var items = await appUserClient.FoldersManager.GetFolderItemsAsync(FolderId, 500,0, responeParam, false, BoxSortBy.Name.ToString(), BoxSortDirection.DESC);

I am using the following to retrieve the content of a specific folder sorted by date;

var items = await appUserClient.FoldersManager.GetFolderItemsAsync(FolderId, 500,0, responeParam, false, BoxSortBy.interacted_at.ToString(), BoxSortDirection.DESC);
and I get the below error;

**Error Details;**

Box.V2.Exceptions.BoxException
  HResult=0x80131500
  Message=The API returned an error [BadRequest | wcapwmglgn74olg4.03e565b5abf906c7165cc9e64c71e2c2f] bad_request - Bad Request
  Source=Box.V2.Core
  StackTrace:
   at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)
   at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Box.V2.Managers.BoxFoldersManager.<GetFolderItemsAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<Main>d__0.MoveNext() in C:\Visual Studio Projects\ConsoleApp2\ConsoleApp1\ConsoleApp1\Program.cs:line 37

  This exception was originally thrown at this call stack:
    [External Code]
    ConsoleApp1.Program.Main(string[]) in Program.cs

**Comment by stevebrownlou** [comment]
Having the same issue.
Would also like to sort by size, modified_at or created_at if possible.
