### ISSUE TITLE
Error in setting ID property using BoxEntity Class

### ISSUE THREAD

**Issue by mohit-spec** [box/box-windows-sdk-v2#73]
When i am calling my webservice from my application at that time it gives me following error:

System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.InvalidOperationException: Cannot deserialize type 'Box.V2.Models.BoxEntity' because it contains property 'Id' which has no public setter.

System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.InvalidOperationException: Cannot deserialize type 'Box.V2.Models.BoxEntity' because it contains property 'Id' which has no public setter.

   at System.Xml.Serialization.TypeScope.GetSettableMembers(StructMapping mapping, ArrayList list)

   at System.Xml.Serialization.TypeScope.GetSettableMembers(StructMapping mapping, ArrayList list)

   at System.Xml.Serialization.TypeScope.GetSettableMembers(StructMapping mapping, ArrayList list)

   at System.Xml.Serialization.TypeScope.GetSettableMembers(StructMapping structMapping)

   at System.Xml.Serialization.TypeScope.GetSettableMembers(StructMapping mapping, Dictionary`2 memberInfos)

   at System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(StructMapping structMapping)

   at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateMethod(TypeMapping mapping)

   at System.Xml.Serialization.XmlSerializationILGen.GenerateReferencedMethods()

   at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(String[] methods, XmlMapping[] xmlMappings, Type[] types)

   at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence)

   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)

   at System.Xml.Serialization.XmlSerializer.FromMappings(XmlMapping[] mappings, Type type)

   at System.Web.Services.Protocols.SoapServerType..ctor(Type type, WebServiceProtocols protocolsSupported)

   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()

   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing)

   --- End of inner exception stack trace ---

When i tried to find rootcause of this problem i've found that BoxEntity class has no setter property defined for ID and Type. 

anyone can help ??

**Comment by brianytang** [comment]
I'm a little confused about what you are trying to do. 

It sounds like you're trying to deserialize  SOAP responses from your webservice using the Box Entities included in the SDK. Is there a reason you are not making requests against the actual Box API?
