### ISSUE TITLE
Cancel Sign Request

### ISSUE THREAD

**Issue by i-tachiiri** [box/box-windows-sdk-v2#929]
- [○ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [○] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [○] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [○] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am encountering an issue when using the CancelSignRequestAsync method from the Box Windows SDK v2 as documented here: [Box Windows SDK v2 documentation for Cancel Sign Request](https://github.com/box/box-windows-sdk-v2/blob/main/docs/sign-requests.md#cancel-sign-request). When I attempt to cancel a sign request, I receive a 'Bad request [SignRequestId]' error.

However, when I use the GetSignRequestByIdAsync method with the same ID, it returns the expected results correctly. The sign request is in a status where someone is yet to sign it, and both the creation and cancellation of the sign request are being done through the same API.

Is this function currently usable? If it is, could you advise on any additional information or steps that need to be provided or verified to resolve this error message?

### Expected Behavior
Cancel Sign Request by ID

### Error Message, Including Stack Trace
BoxAPIException: The API returned an error [BadRequest | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx] bad_request - Bad request
※xxxx... is Sign Request ID

#### StackTrace
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at 取引先登録CSV生成ツール.Form1.btn_addNew_Click(Object sender, EventArgs e) in C:\work\取引先登録CSV生成ツール\取引先登録CSV生成ツール\Form1.cs:line 256
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)

### Versions Used
.Net SDK: 6.0
Windows: Windows10 22H2

**Comment by arjankowski** [comment]
Hi @i-tachiiri,

Does the issue you mentioned still occurs?
 
On my end, I tried to reproduce it locally, but both `GetSignRequestByIdAsync` and `CancelSignRequestAsync` work fine on my environment.

Could you please review [this page here ](https://developer.box.com/guides/box-sign/cancel-sign-request/) and ensure that SignRequest has the appropriate status, and that the user who created the request is the same who try is trying to to cancel it?

Regards,
Artur
